@host = http://127.0.0.1:8000
@react_base_url = {{host}}/api
@public_header = Content-Type: applicatio/json\r\nAccept: application/json\r\nAccept-Language: en
@auth_user_header = Content-Type: application/json\r\nAccept: application/json\r\nAccept-Language: en\r\nAuthorization: Bearer 1|YngJvk5VgZwI0ad0oFBH7IkiOfTBenqGVy8rogTd
@auth_admin_header = Content-Type: application/json\r\nAccept: application/json\r\nAccept-Language: en\r\nAuthorization: Bearer 2|Q8dU8lBQIijBiysui3JKswJBRIC5dLoWMuZ9zayr
#-------PING------------#
###

//-----------------------------------------------------------------User's apis-------------------------------------------------------

# @name userRegister
POST {{react_base_url}}/UserRegister HTTP/1.1
{{public_header}}

{ 
    "first_name":"sid",
    "last_name":"shukla",
    "email":"sidshukla@gmail.com",
    "password":"sidshukla123@gmail.com",
    "password_confirmation":"sidshukla123@gmail.com"
}
###

# @name userLogin
POST {{react_base_url}}/UserLogin HTTP/1.1
{{public_header}}

{
    "email":"sidshukla@gmail.com",
    "password":"sidshukla123@gmail.com"
}

###

# @name userprofile
POST {{react_base_url}}/UserProfile HTTP/1.1
{{auth_user_header}}
###

# @name userlogout
POST {{react_base_url}}/UserLogout HTTP/1.1
{{auth_user_header}}
###

# @name storeBlogpost
POST {{react_base_url}}/blogpost/storeBlogpost HTTP/1.1
{{auth_user_header}}

{
    "blogpost_name":"Technical_third",
    "category_id":1,
    "blogpost_desc":"Hey, i am posting a blog regarding to some technical knowladge hope yoy find it helpful",
    "upload_file":"hhaa//ad/ad/dad/dad/ad"
}
###

# @name showBlogpost
POST {{react_base_url}}/blogpost/showBlogpost HTTP/1.1
{{auth_user_header}}

###

# @name myBlogpost
POST {{react_base_url}}/blogpost/myBlogpost HTTP/1.1
{{auth_user_header}}

###

# @name updateBlogpost
POST {{react_base_url}}/blogpost/updateBlogpost/1 HTTP/1.1
{{auth_user_header}}

{
    "blogpost_name":"Technical_fir",
    "category_id":1,
    "blogpost_desc":"Hey, i am posting a blog regarding to some technical knowladge hope you find it helpful",
    "upload_file":"/facade/assets/image/api.png"
}
###

# @name doLike
POST {{react_base_url}}/like/doLike HTTP/1.1
{{auth_user_header}}

{
    "user_id":1,
    "blogpost_id":3
}

###

# @name doComment
POST {{react_base_url}}/comment/doComment HTTP/1.1
{{auth_user_header}}

{
    "user_id":1,
    "blogpost_id":3,
    "comment":"Nices f fwkfnkwjnfkwd"
}

###

# @name allLike
POST {{react_base_url}}/like/allLike HTTP/1.1
{{auth_user_header}}

###

# @name allComment
POST {{react_base_url}}/comment/allComment HTTP/1.1
{{auth_user_header}}

###

//-----------------------------------------------------------------Admin's api-------------------------------------------------------

# @name AdminRegister
POST {{react_base_url}}/AdminRegister HTTP/1.1
{{public_header}}

{ 
    "first_name":"ravindra",
    "last_name":"ravindra",
    "email":"ravindraunuri@gmail.com",
    "password":"ravindraunuri@2002",
    "password_confirmation":"ravindraunuri@2002"
}
###

# @name AdminLogin
POST {{react_base_url}}/AdminLogin HTTP/1.1
{{public_header}}

{
    "email":"ravindraunuri@gmail.com",
    "password":"ravindraunuri@2002"
}

###

# @name Adminprofile
POST {{react_base_url}}/AdminProfile HTTP/1.1
{{auth_admin_header}}
###

# @name Adminlogout
POST {{react_base_url}}/AdminLogout HTTP/1.1
{{auth_admin_header}}
###

# @name blogpostCategoryCreate
POST {{react_base_url}}/blogpostCategory/createCategory HTTP/1.1
{{auth_admin_header}}

{
    "category_name":"Technical"
}
###
