@host = http://127.0.0.1:8000
@react_base_url = {{host}}/api
@public_header = Content-Type: applicatio/json\r\nAccept: application/json\r\nAccept-Language: en
@auth_user_header = Content-Type: application/json\r\nAccept: application/json\r\nAccept-Language: en\r\nAuthorization: Bearer 4|UPQJLd4YsBPlyfZ5oGQH466EmAbYReKCELa4zkuS
@auth_admin_header = Content-Type: application/json\r\nAccept: application/json\r\nAccept-Language: en\r\nAuthorization: Bearer 7|QdYvpZQRCiwWYLffsmysBUbtK5I6uXLJRabtL13B
#-------PING------------#
###

//-----------------------------------------------------------------User's apis-------------------------------------------------------

# @name userRegister
POST {{react_base_url}}/UserRegister HTTP/1.1
{{public_header}}

{ 
    "first_name":"Montu",
    "last_name":"Jain",
    "email":"montujain2618@gmail.com",
    "password":"zxcvbnm10213$",
    "password_confirmation":"zxcvbnm10213$"
}
###

# @name userLogin
POST {{react_base_url}}/UserLogin HTTP/1.1
{{public_header}}

{
    "email":"montujain2618@gmail.com",
    "password":"zxcvbnm12013$"
}
###

# @name myProfile
POST {{react_base_url}}/MyProfile HTTP/1.1
{{auth_user_header}}
###

# @name updateUser
POST {{react_base_url}}/updateUser HTTP/1.1
{{auth_user_header}}

{ 
    "first_name":"Ravind",
    "last_name":"Unur",
    "email":"ravindanuri@gmail.com"
}
###

# @name updatePassword
POST {{react_base_url}}/updatePassword HTTP/1.1
{{auth_user_header}}

{ 
    "old_password":"zxcvbnm1013$",
    "password":"zxcvbnm12013$",
    "password_confirmation":"zxcvbnm12013$"
}
###

# @name userlogout
POST {{react_base_url}}/UserLogout HTTP/1.1
{{auth_user_header}}
###

# @name get
POST {{react_base_url}}/get HTTP/1.1
{{auth_user_header}}
###

# @name storeBlogpost
POST {{react_base_url}}/blogpost/storeBlogpost HTTP/1.1
{{auth_user_header}}

{
    "blogpost_name":"Technical",
    "category_id":1,
    "blogpost_desc":"Hey, i am jay lathiya",
    "upload_file":"hhaa//ad/ad/dad/dad/ad"
}
###

# @name showBlogpost
POST {{react_base_url}}/blogpost/showBlogpost HTTP/1.1
{{auth_user_header}}

###

# @name myBlogpost
POST {{react_base_url}}/blogpost/myBlogpost HTTP/1.1
{{auth_user_header}}

###

# @name updateBlogpost
POST {{react_base_url}}/blogpost/updateBlogpost/2 HTTP/1.1
{{auth_user_header}}

{
    "blogpost_name":"Technical_fir",
    "category_id":1,
    "blogpost_desc":"Hey, i am posting a blog regarding to some technical knowladge hope you find it helpful",
    "upload_file":"/facade/assets/image/api.png"
}
###

# @name deleteBlogpost
POST {{react_base_url}}/blogpost/deleteBlogpost/1 HTTP/1.1
{{auth_user_header}}
###

# @name doLike
POST {{react_base_url}}/like/doLike/7 HTTP/1.1
{{auth_user_header}}

###

# @name allLike
POST {{react_base_url}}/like/allLike HTTP/1.1
{{auth_user_header}}

###

# @name likeDetail
POST {{react_base_url}}/like/likeDetail/3 HTTP/1.1
{{auth_user_header}}

###

# @name dislike
POST {{react_base_url}}/like/dislike/7 HTTP/1.1
{{auth_user_header}}

###

# @name doComment
POST {{react_base_url}}/comment/doComment/9 HTTP/1.1
{{auth_user_header}}

{
    "comment":"Nices jay lathiya"
}

###

# @name commentDetail
POST {{react_base_url}}/comment/commentDetail/3 HTTP/1.1
{{auth_user_header}}
###

# @name deleteComment
POST {{react_base_url}}/comment/deleteComment/4 HTTP/1.1
{{auth_user_header}}
###

# @name allComment
POST {{react_base_url}}/comment/allComment HTTP/1.1
{{auth_user_header}}

###

# @name follow
POST {{react_base_url}}/followcontrol/follow/23 HTTP/1.1
{{auth_user_header}}

###

# @name Unfollow
DELETE  {{react_base_url}}/followcontrol/unfollow/3 HTTP/1.1
{{auth_user_header}}

###


//-----------------------------------------------------------------Admin's api-------------------------------------------------------

# @name AdminRegister
POST {{react_base_url}}/AdminRegister HTTP/1.1
{{public_header}}

{ 
    "first_name":"ravindra",
    "last_name":"ravindra",
    "email":"ravindraunuri@gmail.com",
    "password":"ravindraunuri@2002",
    "password_confirmation":"ravindraunuri@2002"
}
###

# @name AdminLogin
POST {{react_base_url}}/AdminLogin HTTP/1.1
{{public_header}}

{
    "email":"ravindraunuri@gmail.com",
    "password":"ravindraunuri@2002"
}

###

# @name Adminprofile
POST {{react_base_url}}/AdminProfile HTTP/1.1
{{auth_admin_header}}
###

# @name Adminlogout
POST {{react_base_url}}/AdminLogout HTTP/1.1
{{auth_admin_header}}
###

# @name blogpostCategoryCreate
POST {{react_base_url}}/blogpostCategory/createCategory HTTP/1.1
{{auth_admin_header}}

{
    "category_name":"Technica"
}
###

# @name updateCategory
POST {{react_base_url}}/blogpostCategory/updateCategory/2 HTTP/1.1
{{auth_admin_header}}

{
    "category_name":"Tech"
}
###

# @name deleteCategory
POST {{react_base_url}}/blogpostCategory/deleteCategory/2 HTTP/1.1
{{auth_admin_header}}

###
